[package]
name = "go-compiler"
version = "0.1.0"
authors = ["Angus Holder <aholder97@gmail.com>"]

[dependencies]
num-traits = "*"
vec_map = "*"
smallvec = "*"
string-interner = "*"
fnv = "*"
backtrace = "*"